package com.rakovets.course.challenge.exception;

import javax.management.monitor.StringMonitor;

//public class Task1 {
    //public static void main(String[] args) {
        //try {
            //String pustayaStroka = null;
          //  System.out.println(pustayaStroka.trim());
        //} catch (java.lang.Exception ex) {
            //System.out.printf("You have exception: %s ", ex);
          //  ex.printStackTrace();
        //}
        //try {
            //int[] numbers = new int[5];
            //numbers[4] = 77;
          //  System.out.println(numbers[7]);
        //} catch (Exception ex) {
          //  ex.printStackTrace();
        //} finally {
      //      System.out.println("Блок finally");
    //    }
  //      System.out.println("Программа завершена");    }
//}